"""SQLite schema modelled on PeopleSoft HCM record names (PS_JOB, PS_PERSONAL_DATA, ...)."""
import sqlite3
import threading
from datetime import datetime, timezone

from .config import config

_lock = threading.RLock()

SCHEMA = """
CREATE TABLE IF NOT EXISTS PS_PERSONAL_DATA (
  EMPLID TEXT PRIMARY KEY,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  MIDDLE_NAME TEXT DEFAULT '',
  PREF_FIRST_NAME TEXT DEFAULT '',
  NAME_DISPLAY TEXT NOT NULL,
  BIRTHDATE TEXT,
  SEX TEXT DEFAULT 'U',
  COUNTRY TEXT DEFAULT 'USA',
  LAST_UPDATE_DTTM TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS PS_EMAIL_ADDRESSES (
  EMPLID TEXT NOT NULL, E_ADDR_TYPE TEXT NOT NULL, EMAIL_ADDR TEXT NOT NULL,
  PREF_EMAIL_FLAG TEXT DEFAULT 'N', PRIMARY KEY (EMPLID, E_ADDR_TYPE)
);
CREATE TABLE IF NOT EXISTS PS_PERSON_PHONE (
  EMPLID TEXT NOT NULL, PHONE_TYPE TEXT NOT NULL, PHONE TEXT NOT NULL,
  PREF_PHONE_FLAG TEXT DEFAULT 'N', PRIMARY KEY (EMPLID, PHONE_TYPE)
);
CREATE TABLE IF NOT EXISTS PS_PERS_NID (
  EMPLID TEXT NOT NULL, COUNTRY TEXT NOT NULL, NATIONAL_ID_TYPE TEXT NOT NULL,
  NATIONAL_ID TEXT NOT NULL, PRIMARY KEY (EMPLID, COUNTRY, NATIONAL_ID_TYPE)
);
CREATE TABLE IF NOT EXISTS PS_EMPLOYMENT (
  EMPLID TEXT NOT NULL, EMPL_RCD INTEGER NOT NULL DEFAULT 0,
  HIRE_DT TEXT, ORIG_HIRE_DT TEXT, REHIRE_DT TEXT, TERMINATION_DT TEXT, LAST_DATE_WORKED TEXT,
  PRIMARY KEY (EMPLID, EMPL_RCD)
);
CREATE TABLE IF NOT EXISTS PS_JOB (
  EMPLID TEXT NOT NULL, EMPL_RCD INTEGER NOT NULL DEFAULT 0,
  EFFDT TEXT NOT NULL, EFFSEQ INTEGER NOT NULL DEFAULT 0,
  ACTION TEXT NOT NULL, ACTION_REASON TEXT DEFAULT '', ACTION_DT TEXT,
  DEPTID TEXT, JOBCODE TEXT, POSITION_NBR TEXT DEFAULT '', LOCATION TEXT,
  COMPANY TEXT, BUSINESS_UNIT TEXT, SETID_DEPT TEXT DEFAULT 'SHARE',
  EMPL_STATUS TEXT NOT NULL, HR_STATUS TEXT NOT NULL,
  REG_TEMP TEXT DEFAULT 'R', FULL_PART_TIME TEXT DEFAULT 'F', EMPL_CLASS TEXT DEFAULT 'E',
  SUPERVISOR_ID TEXT DEFAULT '', REPORTS_TO TEXT DEFAULT '',
  COMPRATE REAL DEFAULT 0, CURRENCY_CD TEXT DEFAULT 'USD', COMP_FREQUENCY TEXT DEFAULT 'A',
  STD_HOURS REAL DEFAULT 40, PAYGROUP TEXT DEFAULT 'KU1',
  LASTUPDDTTM TEXT NOT NULL, LASTUPDOPRID TEXT DEFAULT 'PS',
  PRIMARY KEY (EMPLID, EMPL_RCD, EFFDT, EFFSEQ)
);
CREATE TABLE IF NOT EXISTS PS_DEPT_TBL (
  SETID TEXT DEFAULT 'SHARE', DEPTID TEXT PRIMARY KEY, DESCR TEXT NOT NULL,
  MANAGER_ID TEXT DEFAULT '', LOCATION TEXT, COMPANY TEXT, EFF_STATUS TEXT DEFAULT 'A'
);
CREATE TABLE IF NOT EXISTS PS_JOBCODE_TBL (
  SETID TEXT DEFAULT 'SHARE', JOBCODE TEXT PRIMARY KEY, DESCR TEXT NOT NULL,
  DESCRSHORT TEXT, GRADE TEXT, JOB_FAMILY TEXT, MANAGER_LEVEL TEXT DEFAULT ''
);
CREATE TABLE IF NOT EXISTS PS_LOCATION_TBL (
  SETID TEXT DEFAULT 'SHARE', LOCATION TEXT PRIMARY KEY, DESCR TEXT NOT NULL,
  CITY TEXT, STATE TEXT, COUNTRY TEXT
);
CREATE TABLE IF NOT EXISTS PS_COMPANY_TBL (COMPANY TEXT PRIMARY KEY, DESCR TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS PSOPRDEFN (
  OPRID TEXT PRIMARY KEY, SCIM_ID TEXT UNIQUE, EMPLID TEXT DEFAULT '',
  OPRDEFNDESC TEXT, EMAILID TEXT, FIRST_NAME TEXT, LAST_NAME TEXT,
  ACCTLOCK INTEGER DEFAULT 0, EXTERNAL_ID TEXT, RAW_JSON TEXT,
  CREATED_DTTM TEXT, LASTUPDDTTM TEXT, LASTSIGNONDTTM TEXT
);
CREATE TABLE IF NOT EXISTS PSROLEUSER (ROLEUSER TEXT NOT NULL, ROLENAME TEXT NOT NULL, PRIMARY KEY (ROLEUSER, ROLENAME));
CREATE TABLE IF NOT EXISTS PS_OKTA_EVENTS (
  EVENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EMPLID TEXT NOT NULL, EVENT_TYPE TEXT NOT NULL, ACTION TEXT, ACTION_REASON TEXT, EFFDT TEXT,
  SUMMARY TEXT, PAYLOAD TEXT NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'PENDING', ATTEMPTS INTEGER DEFAULT 0,
  CREATED_DTTM TEXT NOT NULL, SENT_DTTM TEXT, TARGET TEXT, REQUEST_PREVIEW TEXT, RESPONSE TEXT
);
CREATE TABLE IF NOT EXISTS PS_AUDIT_LOG (
  AUDIT_ID INTEGER PRIMARY KEY AUTOINCREMENT, EMPLID TEXT, ACTION TEXT, DETAIL TEXT,
  OPRID TEXT, SOURCE TEXT, CREATED_DTTM TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS PS_SEQUENCES (NAME TEXT PRIMARY KEY, NEXT_VAL INTEGER NOT NULL);
"""


def now_iso():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def connect(path=None):
    path = path or config.db_path
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path), timeout=30, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


MIGRATIONS = [
    ("PSOPRDEFN", "LASTSIGNONDTTM", "ALTER TABLE PSOPRDEFN ADD COLUMN LASTSIGNONDTTM TEXT"),
]


def init_db(conn):
    with _lock:
        conn.executescript(SCHEMA)
        for table, column, ddl in MIGRATIONS:
            cols = [r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()]
            if column not in cols:
                conn.execute(ddl)
        conn.commit()


def next_val(conn, name, start=100001):
    with _lock:
        row = conn.execute("SELECT NEXT_VAL FROM PS_SEQUENCES WHERE NAME=?", (name,)).fetchone()
        if row is None:
            conn.execute("INSERT INTO PS_SEQUENCES (NAME, NEXT_VAL) VALUES (?, ?)", (name, start + 1))
            return start
        conn.execute("UPDATE PS_SEQUENCES SET NEXT_VAL=NEXT_VAL+1 WHERE NAME=?", (name,))
        return row["NEXT_VAL"]


def audit(conn, emplid, action, detail, oprid="PS", source="UI"):
    conn.execute(
        "INSERT INTO PS_AUDIT_LOG (EMPLID, ACTION, DETAIL, OPRID, SOURCE, CREATED_DTTM) VALUES (?,?,?,?,?,?)",
        (emplid, action, detail, oprid, source, now_iso()),
    )


def is_seeded(conn):
    return conn.execute("SELECT COUNT(*) FROM PS_PERSONAL_DATA").fetchone()[0] > 0


def reset_db(conn):
    with _lock:
        for (name,) in conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").fetchall():
            conn.execute(f"DROP TABLE IF EXISTS {name}")
        conn.commit()
        init_db(conn)


def rows(conn, sql, params=()):
    return [dict(r) for r in conn.execute(sql, params).fetchall()]


def row(conn, sql, params=()):
    r = conn.execute(sql, params).fetchone()
    return dict(r) if r else None
